# Form implementation generated from reading ui file '.\ui\SupplierDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 304)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_supplier = QtWidgets.QLineEdit(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_supplier.sizePolicy().hasHeightForWidth())
        self.txt_supplier.setSizePolicy(sizePolicy)
        self.txt_supplier.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_supplier.setObjectName("txt_supplier")
        self.gridLayout.addWidget(self.txt_supplier, 1, 1, 1, 1)
        self.bt_delete = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_delete.sizePolicy().hasHeightForWidth())
        self.bt_delete.setSizePolicy(sizePolicy)
        self.bt_delete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_delete.setStyleSheet("margin-top: 3px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../assets/delete-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_delete.setIcon(icon)
        self.bt_delete.setIconSize(QtCore.QSize(32, 32))
        self.bt_delete.setObjectName("bt_delete")
        self.gridLayout.addWidget(self.bt_delete, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.bt_search = QtWidgets.QPushButton(parent=Dialog)
        self.bt_search.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_search.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../assets/search-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_search.setIcon(icon1)
        self.bt_search.setIconSize(QtCore.QSize(16, 16))
        self.bt_search.setObjectName("bt_search")
        self.gridLayout.addWidget(self.bt_search, 1, 2, 1, 1)
        self.list_suppliers = QtWidgets.QListView(parent=Dialog)
        self.list_suppliers.setAlternatingRowColors(True)
        self.list_suppliers.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.list_suppliers.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.list_suppliers.setItemAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.list_suppliers.setObjectName("list_suppliers")
        self.gridLayout.addWidget(self.list_suppliers, 2, 0, 1, 3)
        self.label.setBuddy(self.txt_supplier)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txt_supplier, self.bt_search)
        Dialog.setTabOrder(self.bt_search, self.list_suppliers)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fornecedores"))
        self.bt_delete.setText(_translate("Dialog", "DELETAR"))
        self.label.setText(_translate("Dialog", "FORNECEDOR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
